name: task_sapp
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=3.0.0-287.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_slidable: ^1.0.0
  sqflite: any
  sqflite_common_ffi: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Satisfy
      fonts:
        - asset: fonts/Satisfy-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: Righteous
      fonts:
        - asset: fonts/Righteous-Regular.ttf

    - family: Lexend
      fonts:
        - asset: fonts/Lexend-VariableFont_wght.ttf

    - family: Anaheim
      fonts:
        - asset: fonts/Anaheim-Regular.ttf

    - family: Solway
      fonts:
        - asset: fonts/Solway-Bold.ttf

    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-VariableFont_wght.ttf
          weight: 700
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
